; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_extra_dirs = vendor
lib_deps =
    wire
    ArduinoJson
    RadioLib
    ESPAsyncWebServer
    AsyncTCP
    TinyGPSPlus
    esp32time


; Host-native test environment to run unit tests without hardware
[env:native]
platform = native
;platform = seeed_xiao_esp32s3
; Do not build the Arduino src/ for host tests
test_build_src = no
